services:
  - docker:dind

docker_build:
  image: docker:latest
  stage: build
  when: manual # currently disabled - publish via GitHub
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
  script:  
    - docker build . --tag vvthromildner/$DockerProjectName:$(date +%s) --tag vvthromildner/$DockerProjectName:latest
    - docker push vvthromildner/$DockerProjectName -a
